{
	"version": 1539687869,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/bullet-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemybullet-sheet0.png",
		"images/star-sheet0.png",
		"images/tiledbackground.png",
		"images/playerlives.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/indriver-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/gameover-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/appstore-sheet0.png",
		"images/googleplay-sheet0.png",
		"media/start cut.m4a",
		"media/start cut.ogg",
		"media/8bit-laser-shot-01.m4a",
		"media/8bit-laser-shot-01.ogg",
		"media/8bit-laser-shot-02.m4a",
		"media/8bit-laser-shot-02.ogg",
		"media/game-over.ogg",
		"media/game-over2.m4a",
		"media/end.m4a",
		"media/end.ogg",
		"media/end hard-rock-intro norm.m4a",
		"media/end hard-rock-intro norm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}